NUM_STATES: int = 0
PROGRAM_STR: int = 1
STRIP_1ST_LINE: int = 1
NEXT: int = 1
PREV: int = -1
LOOP_END: int = -1
KEY: int = 0
VALUE: int = 1
OFF: int = 46
ON: int = 18
HALT: str = 'h'
CHAR_SET: str = "!<>[]"
RM_CHARSET: str = "!<>\\[\\]"
RM_REPSTR: str = "^([%s]+,\\s*\\d+)$" % RM_CHARSET
RM_DEFINE: str = "^(\\w+)$"
RM_DEFFILE: str = "^(\\w+:\\s*[%s]*)$" % RM_CHARSET
RM_DEFFILE_BR: str = "^(\\w+:\\s*[%s{}\\s\\w,]+)$" % RM_CHARSET